#!/bin/bash
#Ben Cradick
#cs 2750
#3-28-18

 function handleInterrupt() {
     rm names3
     exit
 }
# function genNames {

# }
trap handleInterrupt SIGINT
# awk 'BEGIN { FS=","} { print $2 " "  $1 }' names.txt |\
# sed "s/^[ \t]*//"  |\
# awk '{print $1 " " $NF}' |\
# sed 's/[^a-zA-Z ]//g' |\
# sed 's/\b\([[:alpha:]]\)\([[:alpha:]]*\)\b/\u\1\L\2/g' > names2.txt
collisions=0;
linecount=`wc -l names3.txt | awk '{print $1}'`

rm names4
cp names3.txt names4
i=1

while (($i <= $linecount + 1)); do
    first=`sed  "$i"'q;d' names4 | awk '{print tolower($1)}' | cut -c-8`
    last=`sed  "$i"'q;d' names4 | awk '{print tolower($2)}'| cut -c-8`
    
    
    ((collisions++));
    #echo $collisions
    if (! grep -q "$first" names4 ); then
        sed -i "$i"'s/$/ '"$first"'/' names4
    elif (! grep -q "$last" names4 ); then
        sed  -i "$i"'s/$/ '"$last"'/' names4 
    fi
     ((i++))
done





