#!/bin/bash
#Ben Cradick
#cs 2750
#3-28-18

 function handleInterrupt() {
     rm names4
     exit
 }
 function collision() {
     ((collisions++));
 }
# function genNames {

# }
trap handleInterrupt SIGINT
# awk 'BEGIN { FS=","} { print $2 " "  $1 }' names.txt |\
# sed "s/^[ \t]*//"  |\
# awk '{print $1 " " $NF}' |\
# sed 's/[^a-zA-Z ]//g' |\
# sed 's/\b\([[:alpha:]]\)\([[:alpha:]]*\)\b/\u\1\L\2/g' > names2.txt
collisions=0;
linecount=`wc -l names3.txt | awk '{print $1}'`

rm names4
cp names3.txt names4
i=1

while (($i <= $linecount + 1)); do
    username=`sed  "$i"'q;d' names4 | awk '{print tolower($1)}' | cut -c-8`
    
    #echo $collisions
    if (! grep -q "$username" names4 ); then
        sed -i "$i"'s/$/ '"$username"'/' names4
    else
        username=`sed  "$i"'q;d' names4 | awk '{print tolower($2)}'| cut -c-8`
        collision
        if (! grep -q "$username" names4 ); then
             sed  -i "$i"'s/$/ '"$username"'/' names4 
        else
        collision
        username=`awk -v i="$i" 'NR == i {print tolower(substr($2,1,1) $1); exit}' names4 | cut -c-8`
            if (! grep -q "$username" names4 ); then
                sed -i "$i"'s/$/ '"$username"'/' names4
                else
                collision
                username=`awk -v i="$i" 'NR == i {print tolower(substr($1,1,1) $2); exit}' names4 | cut -c-8`
                if (! grep -q "$username" names4 ); then
                    sed -i "$i"'s/$/ '"$username"'/' names4
                    else
                    while (! grep -q "$username" names4 ); do
                    fast=`awk -v i="$i" 'NR == i {print tolower(substr($2,1,1) $1); exit}' names4 | cut -c-6`
                    username=
                fi
            fi    
        fi     
    fi
     ((i++))
done





